# Generated by Django 2.2.2 on 2019-06-15 17:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarParks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpark_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=9)),
                ('location', models.CharField(blank=True, max_length=32)),
                ('spaces', models.PositiveIntegerField(blank=True)),
                ('min_cost_pence', models.PositiveIntegerField(blank=True)),
                ('features', django.contrib.postgres.fields.jsonb.JSONField()),
                ('operator', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
