# Generated by Django 2.2.2 on 2019-06-14 14:43

import os
import json

from django.db import migrations

def populate_parking_db(apps, schema_editor):
    print("Populating car parking DB from JSON file...")

    CarParks = apps.get_model('parking', 'CarParks')
    carparks_json = open(os.path.join(os.getcwd(), 'parking', 'migrations', 'car_parks.json'))

    data = json.load(carparks_json)

    for carpark in data:
        print(".", end="")
        CarParks.objects.create(
            carpark_id=carpark["id"],
            name=carpark["name"],
            postcode=carpark["postcode"],
            address=carpark["address"],
            min_cost_pence=max(0,carpark["min_cost_pence"]),
            location=carpark["location"],
            spaces=carpark["spaces"],
            features=carpark["features"],#'{"some":"json"}',#carpark["features"],            
            operator=carpark["operator"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_parking_db)
    ]
